outputPath = "compare_plot_subleadingeta_run3.root"

taskSetup = {
  "Xmax"   : 1500, 
  "Xmin"   : 0, 
  "Ymin"   : 0,
  "Ymax"   : 0.3,
  "nameX"  : " subleading #eta ", 
  "nameY"  : "Number of Jets",
  "name"   : "subleadingeta", 
  "doLogy" : 0,
  "rebinFactor" : 1,   
  "doFraction"  : 0,
  "doRatio" : 0,
  "masterLabel" : "#nu + LQ(#rightarrow#nu c)",
  "lumi" : -1, #58791.6 + 44630.6 + 33402.2 + 3244.54, #11925.1,
  "cme"  : 13,
  "relErrMax" : 10,
  "scaleToData" : 1,
  "sort" : 1,
  "ratioYLabel" : "",
  "ratioYmin" : 0,
  "ratioYmax" : 2.5,
  "normalized" : 1,
}
compareSources = {
  "1" : { 
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_0p5/out.root",
    "histPath"    :   ["eta2_c"],
    "color"       :   4,
    "style"       :   21,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 0.5 TeV",
  }, 
  "2" : { 
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_1p0/out.root", 
    "histPath"    :   ["eta2_c"],
    "color"       :   2,
    "style"       :   22,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 1 TeV",
  },
  "3" : {
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_1p4/out.root",
    "histPath"    :   ["eta2_c"],
    "color"       :   6,
    "style"       :   23,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 1.4 TeV",
  },
  "4" : {
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_2p0/out.root",
    "histPath"    :   ["eta2_c"],
    "color"       :   7,
    "style"       :   24,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 2 TeV",
  },
  "5" : {
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_2p5/out.root",
    "histPath"    :   ["eta2_c"],
    "color"       :   8,
    "style"       :   25,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 2.5 TeV",
  },
  "6" : {
    "filePath"    :   "/afs/cern.ch/work/s/sgoswami/public/taunvnvlq/run_3p0/out.root",
    "histPath"    :   ["eta2_c"],
    "color"       :   9,
    "style"       :   26,
    "drawOption"  :   "p",
    "legendLabel" :   "m_{LQ} = 3 TeV",
  },
} 
